baseURL = 'https://businessschools.github.io/a'
languageCode = 'en-us'

title = 'HigherEduSpot'

[module]
    [[module.imports]]
        path = "hextra"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false