baseURL = "https://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "hextra"

[module]
    [[module.imports]]
        path = "university"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

enableRobotsTXT = true
enableGitInfo = true
# enableEmoji = false
hasCJKLanguage = true

# [services.googleAnalytics]
# ID = "G-MEASUREMENT_ID"

[outputs]
home = ["HTML"]
page = ["HTML"]
section = ["HTML", "RSS"]

defaultContentLanguage = "en"

[languages.en]
languageName = "English"
weight = 1
title = "Hextra"

[languages.fa]
languageName = "فارسی"
languageCode = "fa"
languageDirection = "rtl"
weight = 2
title = "هگزترا"

[languages.ja]
languageName = "日本語"
languageCode = "ja"
weight = 3
title = "Hextra"

[languages.zh-cn]
languageName = "简体中文"
languageCode = "zh-CN"
weight = 4
title = "Hextra"

[module]
[module.hugoVersion]
extended = true
min = "0.112.0"

workspace = "hugo.work"
imports = [
  { path = "github.com/imfing/hextra" }
]

[markup.highlight]
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true
delimiters = { block = [["\\[", "\\]"], ["$$", "$$"]], inline = [["\\(", "\\)"]] }

enableInlineShortcodes = true

[menu]

[[menu.main]]
identifier = "documentation"
name = "Documentation"
pageRef = "/docs"
weight = 1

[[menu.main]]
identifier = "showcase"
name = "Showcase"
pageRef = "/showcase"
weight = 2

[[menu.main]]
identifier = "blog"
name = "Blog"
pageRef = "/blog"
weight = 3

[[menu.main]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 4

[[menu.main]]
name = "Search"
weight = 5
[menu.main.params]
type = "search"

[[menu.main]]
name = "GitHub"
weight = 6
url = "https://github.com/imfing/hextra"
[menu.main.params]
icon = "github"

[[menu.sidebar]]
identifier = "more"
name = "More"
[menu.sidebar.params]
type = "separator"
weight = 1

[[menu.sidebar]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 2

[[menu.sidebar]]
identifier = "hugoDocs"
name = "Hugo Docs ↗"
url = "https://gohugo.io/documentation/"
weight = 3

[params]
description = "Modern, responsive, batteries-included Hugo theme for creating beautiful static websites."

[params.navbar]
displayTitle = true
displayLogo = true
[params.navbar.logo]
path = "images/logo.svg"
dark = "images/logo-dark.svg"
# width = 40
# height = 20
# link = "/"
width = "wide"

[params.page]
width = "normal"

[params.theme]
default = "system"
displayToggle = true

[params.footer]
enable = true
displayCopyright = true
displayPoweredBy = true
width = "normal"

displayUpdatedDate = true
dateFormat = "January 2, 2006"

[params.search]
enable = true
type = "flexsearch"

[params.search.flexsearch]
index = "content"
tokenize = "forward"

[params.editURL]
enable = true
base = "https://github.com/imfing/hextra/edit/main/exampleSite/content"

[params.blog.list]
displayTags = true
sortBy = "date"
sortOrder = "desc"

[params.highlight.copy]
enable = true
display = "hover"

[params.comments]
enable = false
type = "giscus"

[params.comments.giscus]
repo = "imfing/hextra"
repoId = "R_kgDOJ9fJag"
category = "General"
categoryId = "DIC_kwDOJ9fJas4CY7gW"
